{
 "title": "1_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "dashlist", "gridPos": { "h": 21, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{prettyname}}" }
   ]
  },
  {
   "title": "Coin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{symboltoken}}" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": {
    "content": "Decentralized payment network and supply chain for legal cannabis industry."
   }
  },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_block_height", "legendFormat": "{{time}}" }
   ]
  },
  {
   "title": "Avg. Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_time_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Price",
   "type": "stat",
   "description": "Data provided by CoinGecko",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_crypto{name=\"usd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "node_crypto{name=\"usd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Supply, coins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_bank_bond{param=\"Supply\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Community Pool, coins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_bank_bond{param=\"Community Pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflation",
   "type": "stat",
   "description": "The maximum rate that the Cosmos Hub can mint new ATOMs, proportional to the supply",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "{{inflationmax}}" }
   ]
  },
  {
   "title": "Change (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_crypto{name=\"usd_24h_change\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokenomics, coins",
   "type": "piechart",
   "description": "Validators can have one of three statuses:\n\nUNBONDED: The validator is not in the active set. They cannot sign blocks and do not earn rewards. They can receive delegations.\n\nBONDED: Once the validator receives sufficient bonded tokens they automatically join the active set during EndBlock and their status is updated to Bonded. They are signing blocks and receiving rewards. They can receive further delegations. They can be slashed for misbehavior. Delegators to this validator who unbond their delegation must wait the duration of the UnbondingTime, a chain-specific param, during which time they are still slashable for offences of the source validator if those offences were committed during the period of time that the tokens were bonded.\n    \nUNBONDING: When a validator leaves the active set, either by choice or due to slashing, jailing or tombstoning, an unbonding of all their delegations begins. All delegations must then wait the UnbondingTime before their tokens are moved to their accounts from the BondedPool.",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_bank_bond{param=\"Bond\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "node_bank_bond{param=\"Unbonding\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "node_bank_bond{param=\"Unbonded\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "Volume (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_crypto{name=\"usd_24h_vol\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "node_crypto{name=\"usd_24h_vol\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Market Cap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_crypto{name=\"usd_market_cap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "node_valdators{param=\"IdealActiveSet\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "node_valdators{param=\"RealActiveSet\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "node_valdators{param=\"TotalNumValidators\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "APR",
   "type": "stat",
   "description": "Annual Percentage Rate",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_bank_bond{param=\"APR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_bank_bond{param=\"APR\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "MinStake in Active Set, coins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_valdators{param=\"minStake\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}