{
 "title": "2_Parameters",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "dashlist", "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Native token",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{nativetoken}}" }
   ]
  },
  {
   "title": "Chain ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{chain_id}}" }
   ]
  },
  {
   "title": "Daemon Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{daemonname}}" }
   ]
  },
  {
   "title": "Version Chain",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{ver}}" }
   ]
  },
  {
   "title": "Node Home",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{node_home}}" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{prettyname}}" }
   ]
  },
  {
   "title": "Denom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{denom}}" }
   ]
  },
  {
   "title": "Exponent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{exponent}}" }
   ]
  },
  {
   "title": "Symbol Coin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{symboltoken}}" }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 19, "y": 4 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Cosmos SDK version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{cosmos_sdk}}" }
   ]
  },
  {
   "title": "Tendermint version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{tendermint_version}}" }
   ]
  },
  {
   "title": "Key Algos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{keyalgos}}" }
   ]
  },
  {
   "title": "Slip44",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{slip44}}" }
   ]
  },
  {
   "title": "Bech32 Prefix",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_chain_info", "legendFormat": "{{bech32prefix}}" }
   ]
  },
  {
   "title": "Fees",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "node_chain_info_fees" }
   ]
  },
  {
   "title": "Source",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 3, "y": 14 },
   "targets": [
    { "expr": "node_chain_info_links" }
   ]
  },
  {
   "title": "Binaries",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 3, "y": 20 },
   "targets": [
    { "expr": "node_chain_info_binaries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPC",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 25 },
   "targets": [
    { "expr": "node_chain_info_rpc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GRPC",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 25 },
   "targets": [
    { "expr": "node_chain_info_grpc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "REST",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 25 },
   "targets": [
    { "expr": "node_chain_info_rest", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Explorers",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_chain_info_explorers", "legendFormat": "__auto" }
   ]
  },
  { "title": "Staking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Bond denom",
   "type": "stat",
   "description": "The unit and denomination for the asset bonded in the system",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_staking_max_validator", "legendFormat": "{{bonddenom}}" }
   ]
  },
  {
   "title": "Unbonding Time, day(s)",
   "type": "stat",
   "description": "The time duration required for bonded ATOMs to unbond and become transferrable",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_staking_max_validator", "legendFormat": "{{unbondingtime}}" }
   ]
  },
  {
   "title": "Max Entries",
   "type": "stat",
   "description": "The maximum number of unbondings between a delegator and validator within the unbonding period",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_staking_max_validator", "legendFormat": "{{maxentries}}" }
   ]
  },
  {
   "title": "Staking Parameters",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 44 },
   "targets": [
    { "expr": "node_staking", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Historical Entries",
   "type": "stat",
   "description": "Historical Entries is the number of historical entries to persist",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_staking_max_validator", "legendFormat": "{{historicalentries}}" }
   ]
  },
  {
   "title": "Max Validators",
   "type": "stat",
   "description": "The maximum number of validators that may participate in validating blocks, earning rewards, and governance voting",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_staking_max_validator", "legendFormat": "__auto" }
   ]
  },
  { "title": "Slashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Downtime Jail Duration",
   "type": "stat",
   "description": "The suspension time (aka jail time) for a validator that is offline too long",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_slashing_blk_windows", "legendFormat": "{{downtimejailduration}}" }
   ]
  },
  {
   "title": "Min Signed Per Window",
   "type": "stat",
   "description": "Minimum proportion of blocks signed per window without being slashed",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_slashing_blk_windows", "legendFormat": "{{minsignedperwindow}}" }
   ]
  },
  {
   "title": "Signed Block Window",
   "type": "stat",
   "description": "Window for being offline without being slashed, in blocks",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_slashing_blk_windows", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slashing Parameters",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 55 },
   "targets": [
    { "expr": "node_slashing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slash Fraction Double Sign",
   "type": "stat",
   "description": "Slashing fraction due to double signing",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_slashing_blk_windows", "legendFormat": "{{slashfractiondoublesign}}" }
   ]
  },
  {
   "title": "Slash Fraction Downtime",
   "type": "stat",
   "description": "Slashing fraction due to downtime",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_slashing_blk_windows", "legendFormat": "{{slashfractiondowntime}}" }
   ]
  },
  { "title": "Minting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Mint Denom",
   "type": "stat",
   "description": "Denomination of minted tokens",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "{{mintdenom}}" }
   ]
  },
  {
   "title": "Blocks Per Year",
   "type": "stat",
   "description": "Expected number of blocks per year",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goal Bonded",
   "type": "stat",
   "description": "The target ratio of bonded stake to total supply",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "{{goalbonded}}" }
   ]
  },
  {
   "title": "Minting Parameters",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 66 },
   "targets": [
    { "expr": "node_minting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inflation Max",
   "type": "stat",
   "description": "The maximum rate that the Cosmos Hub can mint new ATOMs, proportional to the supply",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "{{inflationmax}}" }
   ]
  },
  {
   "title": "Inflation Min",
   "type": "stat",
   "description": "The minimum rate that the Cosmos Hub can mint new ATOMs, proportional to the supply",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "{{inflationmin}}" }
   ]
  },
  {
   "title": "Inflation Rate Change",
   "type": "stat",
   "description": "A factor of and limit to the speed at which the Cosmos Hub's inflation rate changes",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_minting_blk_per_year", "legendFormat": "{{inflationratechange}}" }
   ]
  },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Base Proposer Reward",
   "type": "stat",
   "description": "The fixed base reward bonus for the validator proposing a block, as a proportion of transaction fees",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_distrib", "legendFormat": "{{baseproposerreward}}" }
   ]
  },
  {
   "title": "Bonus Proposer Reward",
   "type": "stat",
   "description": "The maximum additional reward bonus for the validator proposing a block, as a proportion of transaction fees",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_distrib", "legendFormat": "{{bonusproposerreward}}" }
   ]
  },
  {
   "title": "Community Tax",
   "type": "stat",
   "description": "The proportion of staking rewards diverted to the community pool",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_distrib", "legendFormat": "{{communitytax}}" }
   ]
  },
  {
   "title": "Distribution Parameters",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 79 },
   "targets": [
    { "expr": "node_distribution", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Withdraw Address Enabled",
   "type": "stat",
   "description": "Determines whether or not delegators may set a separate address for receiving staking rewards",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_distrib", "legendFormat": "{{withdrawaddrenabled}}" }
   ]
  },
  { "title": "Governance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Min Deposit",
   "type": "stat",
   "description": "The minimum deposit required for a proposal to enter the voting period",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_gov", "legendFormat": "{{mindeposit}}" }
   ]
  },
  {
   "title": "Max Deposit Period",
   "type": "stat",
   "description": "The maximum amount of time that a proposal can accept deposit contributions before expiring",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_gov", "legendFormat": "{{maxdepositperiod}}" }
   ]
  },
  {
   "title": "Quorum",
   "type": "stat",
   "description": "The minimum proportion of network voting power required for a governance proposal's outcome to be considered valid",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_gov", "legendFormat": "{{tally_quorum}}" }
   ]
  },
  {
   "title": "Governance Parameters",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 89 },
   "targets": [
    { "expr": "node_governance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threshold",
   "type": "stat",
   "description": "The minimum proportion of participating voting power required for a governance proposal to pass",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_gov", "legendFormat": "{{tally_threshold}}" }
   ]
  },
  {
   "title": "Veto Threshold",
   "type": "stat",
   "description": "The minimum proportion of participating voting power to veto (ie. fail) a governance proposal",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_gov", "legendFormat": "{{tally_veto_threshold}}" }
   ]
  },
  {
   "title": "Voting Period",
   "type": "stat",
   "description": "The maximum amount of time that a proposal can accept votes before the voting period concludes",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "node_gov", "legendFormat": "{{votingperiod}}" }
   ]
  }
 ]
}