{
 "title": "6_Proposals",
 "time": { "from": "2023-07-26T03:40:23.880Z", "to": "2023-07-26T09:40:23.880Z" },
 "panels": [
  { "title": "Current/Last Proposal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "dashlist", "gridPos": { "h": 26, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Current/Last Proposal",
   "type": "table",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "node_proposals_last{tabl=\"tabl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_proposals_last{tabl=\"notabl\"}",
     "legendFormat": "{{name_param}}"
    }
   ]
  },
  {
   "title": "Voted / Total Votes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(tabl) (node_proposals_last{tabl=\"notabl\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(tabl) (node_proposals_last{tabl=\"notabl2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voted / Quorum",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B*100", "type": "math" },
    {
     "expr": "sum by(name_param) (node_governance{name_param=\"Quorum\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decision",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$E/$B*100", "type": "math" },
    { "expression": "($F+$H)/$B*100", "type": "math" },
    {
     "expr": "sum by(name_param) (node_governance{name_param=\"Threshold\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veto",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$E/$A*100", "type": "math" },
    {
     "expr": "sum by(name_param) (node_governance{name_param=\"Veto Threshold\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PreLast Proposal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "PreLast  Proposal",
   "type": "table",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 28 },
   "targets": [
    {
     "expr": "node_proposals_pre_last{tabl=\"tabl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_proposals_pre_last{tabl=\"notabl\"}",
     "legendFormat": "{{name_param}}"
    }
   ]
  },
  {
   "title": "Voted / Total Votes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(tabl) (node_proposals_pre_last{tabl=\"notabl\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(tabl) (node_proposals_pre_last{tabl=\"notabl2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voted / Quorum",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B*100", "type": "math" },
    {
     "expr": "sum by(name_param) (node_governance{name_param=\"Quorum\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decision",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$E/$B*100", "type": "math" },
    { "expression": "($F+$H)/$B*100", "type": "math" },
    {
     "expr": "sum by(name_param) (node_governance{name_param=\"Threshold\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veto",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$E/$A*100", "type": "math" },
    {
     "expr": "sum by(name_param) (node_governance{name_param=\"Veto Threshold\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "All Proposals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Proposals",
   "type": "table",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 55 },
   "targets": [
    {
     "expr": "node_proposals{total_num_proposals!=\"total_num_proposals\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Explorers",
   "type": "table",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_chain_info_explorers", "legendFormat": "__auto" }
   ]
  }
 ]
}